// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBXJ-cO2_jiDAaAs3KaNs3P5TaO8DZvI',
    appId: '1:923264049638:web:2aed62512281388af3b627',
    messagingSenderId: '923264049638',
    projectId: 'f-quiz-app',
    authDomain: 'f-quiz-app.firebaseapp.com',
    storageBucket: 'f-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtg_7X4mtDkdk9s6DTDjqoIMCyDH9pFgE',
    appId: '1:923264049638:android:73da55c985dce3b0f3b627',
    messagingSenderId: '923264049638',
    projectId: 'f-quiz-app',
    storageBucket: 'f-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG65hXc8d0PsyciaRRuUiNQQBCHZ358nE',
    appId: '1:923264049638:ios:0df9c17c51194b62f3b627',
    messagingSenderId: '923264049638',
    projectId: 'f-quiz-app',
    storageBucket: 'f-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.fQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG65hXc8d0PsyciaRRuUiNQQBCHZ358nE',
    appId: '1:923264049638:ios:0df9c17c51194b62f3b627',
    messagingSenderId: '923264049638',
    projectId: 'f-quiz-app',
    storageBucket: 'f-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.fQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcBXJ-cO2_jiDAaAs3KaNs3P5TaO8DZvI',
    appId: '1:923264049638:web:d6e96e118bf5d97af3b627',
    messagingSenderId: '923264049638',
    projectId: 'f-quiz-app',
    authDomain: 'f-quiz-app.firebaseapp.com',
    storageBucket: 'f-quiz-app.firebasestorage.app',
  );
}
